---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudnative-pg
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${AO_NAMESPACE}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: automation-orchestrator-operator
  namespace: ${AO_NAMESPACE}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-automation-orchestrator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: registry.appliance.openshift.com:22625/aap/ansible-automation-platform/automation-orchestrator-operator-index@sha256:42cdbdbda48aa6bc62538e619e1ab053f4a99c086349a7da950f566a6910ce55
  displayName: Automation Orchestrator
  publisher: Red Hat
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-operatorhub
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: registry.appliance.openshift.com:22625/operatorhubio/catalog@sha256:77ce09daeb5283682e1ca0b26dfe207ea16457097eee66966169da88e2035410
  displayName: OperatorHub Community
  publisher: OperatorHub.io
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: cloudnative-pg
  source: cs-operatorhub
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: automation-orchestrator-operator
  namespace: ${AO_NAMESPACE}
spec:
  channel: candidate
  installPlanApproval: Automatic
  name: automation-orchestrator-operator
  startingCSV: automation-orchestrator-operator.v0.0.1
  source: cs-automation-orchestrator
  sourceNamespace: openshift-marketplace
