apiVersion: v1beta1
kind: ApplianceConfig
ocpRelease:
  # binary registry requires 4.21+
  version: "4.21.10"
  channel: stable
  cpuArchitecture: x86_64
enableDefaultSources: false
imageRegistry:
  # use binary registry to avoid nested containers when running the image on Konflux
  useBinary: true
