apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/automation-nexus/aap-appliance?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: aap-appliance
    appstudio.openshift.io/component: aap-appliance-iso-x86-64
    pipelines.appstudio.openshift.io/type: build
  name: aap-appliance-iso-x86-64-on-push
  namespace: nexus-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/nexus-tenant/aap-appliance-iso-x86-64:{{revision}}
  - name: dockerfile
    value: Containerfile.iso
  - name: aap-version
    value: "2.7-next"
  - name: automation-orchestrator-version
    value: main
  - name: ocp-version
    value: "4.21.10"
  timeouts:
    pipeline: 4h
  pipelineRef:
    resolver: bundles
    params:
    - name: name
      value: container-aap-appliance
    - name: bundle
      value: quay.io/aap-ci/tekton-catalog/pipeline/build/container-aap-appliance:0.1@sha256:98c93be8e382a9cfdf8eab646e2d62fa5a094b1e87ee22ca4231796d5364493f
    - name: kind
      value: pipeline
    - name: secret
      value: quay-aap-ci-viewer
  taskRunSpecs:
    - pipelineTaskName: build-images
      stepSpecs:
        - name: build
          computeResources:
            requests:
              memory: 8Gi
            limits:
              memory: 8Gi
  taskRunTemplate:
    serviceAccountName: build-pipeline-aap-appliance-iso-x86-64
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
