---
apiVersion: v1
kind: Namespace
metadata:
  name: ${AAP_NAMESPACE}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ansible-automation-platform-operator
  namespace: ${AAP_NAMESPACE}
spec:
  targetNamespaces:
  - ${AAP_NAMESPACE}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operator-index
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: registry.appliance.openshift.com:22625/redhat/redhat-operator-index@sha256:d8d6c133f1307855eb2f588233c44a5aeb1604d9881ab423144c85355a2818a3
  displayName: Red Hat Operators
  publisher: Red Hat
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ansible-automation-platform-operator
  namespace: ${AAP_NAMESPACE}
spec:
  channel: stable-2.7
  name: ansible-automation-platform-operator
  installPlanApproval: Automatic
  startingCSV: aap-operator.v2.7.0-0.1781122804
  source: redhat-operator-index
  sourceNamespace: openshift-marketplace
