---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudnative-pg
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${AO_NAMESPACE}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: automation-orchestrator-operator
  namespace: ${AO_NAMESPACE}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-automation-orchestrator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: registry.appliance.openshift.com:22625/aap/ansible-automation-platform/automation-orchestrator-operator-index@sha256:f07ab5bbca2e25829aeb8799ae45b49e8101fa5b4bc635574bda38db4e206863
  displayName: Automation Orchestrator
  publisher: Red Hat
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-operatorhub
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: registry.appliance.openshift.com:22625/operatorhubio/catalog@sha256:933fceed172076dd51aeae4b9225c9d46681b7a67d7fe2b3ce0f11872e4612bb
  displayName: OperatorHub Community
  publisher: OperatorHub.io
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: cloudnative-pg
  source: cs-operatorhub
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: automation-orchestrator-operator
  namespace: ${AO_NAMESPACE}
spec:
  channel: candidate
  installPlanApproval: Automatic
  name: automation-orchestrator-operator
  startingCSV: automation-orchestrator-operator.v0.0.1
  source: cs-automation-orchestrator
  sourceNamespace: openshift-marketplace
