---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudnative-pg
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${AO_NAMESPACE}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: automation-orchestrator-operator
  namespace: ${AO_NAMESPACE}
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-automation-orchestrator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: registry.appliance.openshift.com:22625/aap/ansible-automation-platform/automation-orchestrator-operator-index@sha256:83bef141b02484c31b63ea3ad84134cf0cf6c6235f2b875004d508175bc0486f
  displayName: Automation Orchestrator
  publisher: Red Hat
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cs-operatorhub
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: registry.appliance.openshift.com:22625/operatorhubio/catalog@sha256:a63653c1ece0017db24b4a044905845c306e06130ba5199cd6e56909c5e5479a
  displayName: OperatorHub Community
  publisher: OperatorHub.io
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloudnative-pg
  namespace: cloudnative-pg
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: cloudnative-pg
  source: cs-operatorhub
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: automation-orchestrator-operator
  namespace: ${AO_NAMESPACE}
spec:
  channel: candidate
  installPlanApproval: Automatic
  name: automation-orchestrator-operator
  startingCSV: automation-orchestrator-operator.v0.0.1
  source: cs-automation-orchestrator
  sourceNamespace: openshift-marketplace
